- addon/query/odata-adapter.js
- tests/unit/query/odata-adapter-test.js
[TFS#106342](http://dis-tfs:8080/Common/Flex/_workitems?_a=edit&id=106342).
> Fix attribute name serialized and type detected

- addon/serializers/base.js
- addon/serializers/odata.js
[TFS#105835](http://dis-tfs:8080/Common/Flex/_workitems?_a=edit&id=105835).
> Fix polymorphic relationships

- addon/serializers/base.js
> Delete redundant code

- addon/serializers/base.js
[TFS#108125](http://dis-tfs:8080/Common/CASEBERRY/_workitems?_a=edit&id=108125).
> Fix polymorphic pelationships

- addon/models/model.js
- addon/utils/create.js
> Add projectionName inside projection

- addon/query/odata-adapter.js
- addon/utils/information.js
- tests/unit/query/odata-adapter-test.js
- tests/unit/utils/information-test.js
> Edited odata-adapter-test for DetailPredicate().all

- CHANGELOG.md
- app/initializers/flexberry-enum.js
- tests/unit/utils/enum-functions-test.js
Moved enum-functions-test from ember-flexberry
> Add enum-functions-test from ember-flexberry

- CHANGELOG.md
- addon/utils/enum-functions.js
- tests/unit/utils/enum-functions-test.js
> Fix enumCaptions function

- CHANGELOG.md
- addon/stores/base-store.js
- addon/syncer.js
- addon/utils/reload-local-records.js
Specifying of projection is optional now for `syncDown` mehod.
TFS #108074
> Feature optional projections

- CHANGELOG.md
- addon/adapters/odata.js
- addon/query/odata-adapter.js
- tests/unit/query/odata-adapter-test.js
There were not noticed two problems:
* Not used an adapter property `namespace`
* Override function `pathForType` in adapter does not lead to expected results
> URL build in ODataAdapter

- CHANGELOG.md
- addon/mixins/regenerated/models/i-c-s-soft-s-t-o-r-m-n-e-t-business-audit-objects-audit-entity.js
Operation type must be a string.
I wanted to do better...
> Fix audit-entity model

- CHANGELOG.md
- addon/syncer.js
* Change `queryRecord` to `query`.
* Filter jobs by `executionResult`.
> Fix offline syncer

- .ember-cli
- README.md
- tests/dummy/app/templates/application.hbs
- Update README.md
- Update server port & live reload port
- Update Dummy application.hbs
> Feature update readme.md

- CHANGELOG.md
- addon/adapters/offline.js
- addon/instance-initializers/set-singletons.js
- addon/services/dexie.js
- addon/services/syncer.js
- addon/utils/queue.js
- addon/utils/reload-local-records.js
- app/instance-initializers/set-singletons.js
- ember-cli-build.js
- tests/unit/instance-initializers/set-singletons-test.js
Optimize performance for `syncDown` method of `syncer` service.
Also optimize performance of different operations with data in addon by setting some factories as singletons. It optimizes performance of lookup operation for particular factory because new instance of factory class is not creating.
> Feature sync down performance

- CHANGELOG.md
- addon/serializers/offline.js
- addon/services/dexie.js
Now we are setting proper types of polymorphic belongsTo relationships in offline mode
> Set proper types of polymorphic belongsTo relationships

- CHANGELOG.md
- addon/query/indexeddb-adapter.js
- addon/query/js-adapter.js
- tests/unit/CRUD/base/base-reading-data-types-test.js
- tests/unit/query/js-adapter-test.js
Fix querying records by fields of `date` type with query language using complex predicates in offline mode
> Fix querying records by fields of `date` type

- CHANGELOG.md
- addon/query/builder.js
- addon/query/js-adapter.js
- tests/dummy/app/app.js
- tests/dummy/app/models/bot.js
- tests/dummy/app/models/creator.js
- tests/dummy/app/models/custom-inflector-rules.js
- tests/dummy/app/models/customer.js
- tests/dummy/app/models/ember-flexberry-dummy-test-poly-another-child.js
- tests/dummy/app/models/ember-flexberry-dummy-test-poly-base.js
- tests/dummy/app/models/ember-flexberry-dummy-test-poly-child.js
- tests/dummy/app/models/ember-flexberry-dummy-test-poly.js
- tests/dummy/app/models/employee.js
- tests/dummy/app/models/man.js
- tests/dummy/app/models/tag.js
- tests/dummy/app/serializers/ember-flexberry-dummy-test-poly-another-child.js
- tests/dummy/app/serializers/ember-flexberry-dummy-test-poly-base.js
- tests/dummy/app/serializers/ember-flexberry-dummy-test-poly-child.js
- tests/dummy/app/serializers/ember-flexberry-dummy-test-poly-offline.js
- tests/dummy/app/serializers/ember-flexberry-dummy-test-poly.js
- tests/dummy/app/services/store.js
- tests/unit/CRUD/base/base-reading-polymorphic-test.js
- tests/unit/CRUD/odata/odata-reading-polymorphic-test.js
- tests/unit/CRUD/offline/execute-offline-test.js
- tests/unit/CRUD/offline/offline-reading-polymorphic-test.js
- tests/unit/query/indexeddb-adapter-test.js
Add support reading of polymorphic relationships for in-memory joins for offline data
> Add support reading of polymorphic relationships

- CHANGELOG.md
- addon/query/indexeddb-adapter.js
- addon/query/js-adapter.js
- addon/query/odata-adapter.js
- addon/query/predicate.js
- tests/dummy/app/models/customer.js
- tests/dummy/app/models/ember-flexberry-dummy-application-user.js
- tests/unit/query/geography-predicate-test.js
- tests/unit/query/indexeddb-adapter-test.js
- tests/unit/query/js-adapter-test.js
- tests/unit/query/odata-adapter-test.js
Add 'GeographyPredicate' into query language.
> 150508 filter by field geography

- CHANGELOG.md
- addon/mixins/offline-model.js
- addon/models/model.js
- tests/unit/models/model-test.js
TFS: [#155192](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/155192).
> Fix skipping change of relationships for `syncUp`

- CHANGELOG.md
- addon/mixins/audit-model.js
- addon/services/user.js
Fix declaring of current user name in different places of sources
> Fix declaring of current user name in different places

- CHANGELOG.md
- addon/models/model.js
TFS: [#159975](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/159975).
> Fix call `validate` method for `hasMany` relationships

- addon/adapters/odata.js
- tests/unit/odata/odata-ajax-requests-test.js
Add xhrFields and fix order of attributes.
> Upgrade adapter methods

- addon/adapters/odata.js
- addon/models/model.js
- addon/query/odata-adapter.js
- addon/utils/information.js
> Add new types pk

- addon/adapters/odata.js
- addon/adapters/offline.js
- addon/index.js
- addon/stores/base-store.js
- addon/stores/local-store.js
- addon/stores/online-store.js
> Add online store. Add in store metod deleteAllRecords

- CHANGELOG.md
- addon/index.js
- addon/models/model.js
- addon/query/builder.js
- addon/query/odata-adapter.js
- addon/query/predicate.js
- tests/unit/query/builder-test.js
- tests/unit/query/isof-predicate-test.js
- tests/unit/query/odata-adapter-test.js
> The IsOfPredicate for use isof function in OData queries

- CHANGELOG.md
- addon/serializers/base.js
> Add normalize

- CHANGELOG.md
- addon/index.js
- addon/query/indexeddb-adapter.js
- addon/query/js-adapter.js
- addon/query/odata-adapter.js
- addon/query/predicate.js
- tests/unit/query/geometry-predicate.js
- tests/unit/query/indexeddb-adapter-test.js
- tests/unit/query/js-adapter-test.js
- tests/unit/query/odata-adapter-test.js
Аналогично GeographyPredicate.
Связанные изменения на backend:
https://github.com/Flexberry/NewPlatform.Flexberry.ORM/pull/19
https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/pull/11
https://github.com/Flexberry/NewPlatform.Flexberry.ORM.GisPostgresDataService/pull/3
> Geometry type support

- addon/adapters/odata.js
> Fix callFunction and callAction methods in odata adapter

- addon/adapters/odata.js
- tests/unit/odata/odata-ajax-requests-test.js
> methods callEmberOdataFunction and callEmberOdataAction

- CHANGELOG.md
- addon/utils/information.js
https://github.com/Flexberry/ember-flexberry/issues/779
> Add check order property

- addon/mixins/copyable.js
- addon/models/model.js
> Copyable mixin is implemented and base model is extended.

- CHANGELOG.md
- addon/adapters/odata.js
- tests/unit/CRUD/base/base-batch-updating-test.js
Resolve Flexberry/ember-flexberry#851
> Fix `batchUpdate` when only `belongsTo` relationship was changed

- CHANGELOG.md
- addon/services/offline-globals.js
- addon/stores/base-store.js
> Add method getOfflineSchema

- CHANGELOG.md
- addon/adapters/odata.js
fix Flexberry/ember-flexberry#886; fix Flexberry/ember-flexberry#893; fix Flexberry/ember-flexberry#897;
> Fix binded models become unavailable after pushPayload().

- addon/adapters/odata.js
> Update odata error

- addon/adapters/odata.js
Добавлена проверка при конструировании batch-запроса на необходимость добавления мастера в expand.
Fixes #151
> Expand в Batch-запросе

- addon/adapters/odata.js
- addon/adapters/offline.js
> Fix update store in batch

- CHANGELOG.md
- addon/adapters/odata.js
- addon/query/odata-adapter.js
> Feature 157 query odata function

- addon/query/indexeddb-adapter.js
- addon/query/js-adapter.js
- addon/query/odata-adapter.js
- addon/query/predicate.js
- tests/unit/CRUD/base/base-reading-false-predicates-test.js
- tests/unit/CRUD/base/base-reading-true-predicates-test.js
- tests/unit/CRUD/odata/execute-odata-test.js
- tests/unit/CRUD/odata/odata-reading-false-predicates-test.js
- tests/unit/CRUD/odata/odata-reading-true-predicates-test.js
- tests/unit/CRUD/offline/offline-reading-false-predicates-test.js
- tests/unit/CRUD/offline/offline-reading-true-predicates-test.js
- tests/unit/query/indexeddb-adapter-test.js
- tests/unit/query/js-adapter-test.js
- tests/unit/query/odata-adapter-test.js
Close Flexberry/ember-flexberry#1017.
> Add TruePredicate and FalsePredicate

- CHANGELOG.md
- addon/services/syncer.js
- addon/version.js
- bower.json
- package.json
- vendor/ember-flexberry-data/register-version.js
> Fix sync up without jobs
